AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: MultiversX NFT Service

Resources:
  BucketMediaProduction:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nfts-media.elrond.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  BucketMediaProductionPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketMediaProduction
      PolicyDocument:
        Id: bucket-policy
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::nfts-media.elrond.com/*"

  CloudFrontMediaProduction:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        Aliases:
          - nfts-media.elrond.com
        Origins:
          - Id: s3-static-site
            DomainName: nfts-media.elrond.com.s3-website.us-east-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:777241893292:certificate/4fc48d4f-75c1-4bb9-983f-0c49b1fc44e1"
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          MaxTTL: 60
          DefaultTTL: 60
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: s3-static-site

  BucketMediaTestnet:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: testnet-nfts-media.elrond.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  BucketMediaTestnetPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketMediaTestnet
      PolicyDocument:
        Id: bucket-policy
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::testnet-nfts-media.elrond.com/*"

  CloudFrontMediaTestnet:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        Aliases:
          - testnet-nfts-media.elrond.com
        Origins:
          - Id: s3-static-site
            DomainName: testnet-nfts-media.elrond.com.s3-website.us-east-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:777241893292:certificate/4fc48d4f-75c1-4bb9-983f-0c49b1fc44e1"
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          MaxTTL: 60
          DefaultTTL: 60
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: s3-static-site

  BucketMediaDevnet:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: devnet-nfts-media.elrond.com
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  BucketMediaDevnetPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketMediaDevnet
      PolicyDocument:
        Id: bucket-policy
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: "arn:aws:s3:::devnet-nfts-media.elrond.com/*"

  CloudFrontMediaDevnet:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        Aliases:
          - devnet-nfts-media.elrond.com
        Origins:
          - Id: s3-static-site
            DomainName: devnet-nfts-media.elrond.com.s3-website.us-east-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:777241893292:certificate/4fc48d4f-75c1-4bb9-983f-0c49b1fc44e1"
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          MaxTTL: 60
          DefaultTTL: 60
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: s3-static-site
