export const analyticsEventsEnum = [
  'buy',
  'buyNft',
  'buyFor',
  'buySft',
  'bulkBuy',
  'acceptOffer',
  'bid',
  'purchase',
  'auctionToken',
  'listing',
  'listNftOnMarketplace',
  'nftSwap',
  'changePrice',
  'updatePrice',
  'changeListing',
];
